### PR TITLE
String treatments (alleles) implemented for GWAS

### PR DESCRIPTION
**Pull request by joshua-slaughter**
String treatments are now available. 

1.  Modified functions in src/inputs_from_config.jl to cross-reference SnpArrays.snpdata.snp_info to map UInt8 coding to String.
2. These naming conventions do not follow any conventions when determining A1 or A2 however, having the string should be enough given the user will run post-hoc analyses that will tell them which allele is the minor allele in the population that they're interested in.
3. Added helper functions to testutils.jl to allow for checks in test to occur without saving snp_info to arrow taking up unnecessary space in a non-test run.

### CODE REVIEW

**Comment by olivierlabayle** [comment]
Thanks Josh for taking the lead on this, have you checked how much disk and/or memory overhead is generated by the string representation? Could you provide these figures here, for a few chromosomes? 

I will have a look at the code a little later.

**Comment by joshua-slaughter** [comment]
> Thanks Josh for taking the lead on this, have you checked how much disk and/or memory overhead is generated by the string representation? Could you provide these figures here, for a few chromosomes?
> 
> I will have a look at the code a little later.

Will do!

**Comment by joshua-slaughter** [comment]
Just got around to testing this and the overhead is around 17 fold and a significant time increase. I can post the graphics once they submitted jobs finish running, but for now I will just aim to ensure that 0x00 is minor-minor, 0x01 is major-minor, and so on using SnpArrays.jl minorallele() function to check this version should not increase overhead.

**Comment by olivierlabayle** [comment]
Thank you Josh, that helps a lot. Yes 0/1/2 counting minor alleles is definitely the way to go for now. 

Note: In the longer run I think we should build a TMLE process that can read BGEN or BED files straight away. Probably a package similar to TMLECLI.

**Comment by olivierlabayle** [comment]
@joshua-slaughter  should we close this then?

**Pull request closed without merging**
